version: "3"

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: testemed
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my-networks

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    networks:
      - my-networks

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge
